version: '3.8'

services:
  postgres:
    container_name: entrepreneur-platform-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: entrepreneur_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./populate.psql:/docker-entrypoint-initdb.d/populate.psql  # ✅ Ajout du script
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: entrepreneur-platform-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: entrepreneur_platform
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
